
[package]
name = "usbfloppytracer-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.34"
fltk-grid = "0.2.0"
fltk-table = "0.2.2"
fltk-theme = "0.6.0"
